### ISSUE TITLE
Visual bugs when too close to particles

### ISSUE THREAD

**Issue by bondii** [IMP-Engine/Engine#23]
When getting too close to the particles some strange visual bugs can (and probably will) occur.
https://puu.sh/uo6hQ/20f64158f6.mp4

This is only a problem when being closer to the particles than intended, and therefore will not be fixed.

**Comment by Drenata** [comment]
New unwanted behaviour observed:
When the particles are located some distance from the center (I observed this when the box was outside the world cube), the size of the particles are different depending on which direction they are viewed from.

This is similar to the old bug, but this time distance between camera and particle is not the deciding factor.
https://puu.sh/uwDD5/c071c30062.mp4

**Comment by bondii** [comment]
Bugs now fixed.
